# Generated by Django 5.2.7 on 2026-02-26 22:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_subject_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('middle', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1)),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['test_subject_id'], name='core_patien_test_su_7f031d_idx'), models.Index(fields=['national_id'], name='core_patien_nationa_914a52_idx'), models.Index(fields=['last_name', 'first_name'], name='core_patien_last_na_5d3812_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('technician', 'Technician')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_code', models.CharField(help_text='Unique test code, e.g, CBC, GLU, CHOL', max_length=30, unique=True)),
                ('test_name', models.CharField(help_text='Full name of the test (e.g. Complete,Blood Count)', max_length=150)),
                ('department', models.CharField(help_text='Department(e.g, Hematologe, Biochemistry, Immunology)', max_length=100)),
                ('sample_type', models.CharField(blank=True, help_text='e.g, Boold, Serum, Urine', max_length=50, null=True)),
                ('unit', models.CharField(blank=True, help_text='Measurement unit (e.g. mg/dL, IU/L)', max_length=30, null=True)),
                ('reference_range', models.CharField(blank=True, help_text='Example: 4.5 - 10.0 *10^9/L', max_length=120, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost of the test', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('turnaround_time_hours', models.PositiveBigIntegerField(default=24, help_text='Expected time to complete (in hours)')),
                ('active', models.BooleanField(default=True, help_text='Set to False to deactivativate the test')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['department', 'test_name'],
                'indexes': [models.Index(fields=['test_code'], name='core_test_test_co_e2ed0f_idx'), models.Index(fields=['test_name'], name='core_test_test_na_36e1d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientTest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sample_identifier', models.CharField(blank=True, help_text='Sample ID if lab uses one', max_length=80, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('result_valu', models.CharField(blank=True, max_length=200, null=True)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=120, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount as percent (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Price at time request (copied from Test.price)', max_digits=10, null=True, validators=[django.core.validators.MinLengthValidator(Decimal('0.00'))])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Computed price after discount', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to='core.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_records', to='core.test')),
            ],
            options={
                'verbose_name': 'PatientTest',
                'verbose_name_plural': 'PatientTest',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.test')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.laborder')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testparameter')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_valu', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_results', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_results', to=settings.AUTH_USER_MODEL)),
                ('patienttest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.patienttest')),
            ],
            options={
                'permissions': [('approve_testresult', 'Can approve testresult')],
            },
        ),
        migrations.AddIndex(
            model_name='patienttest',
            index=models.Index(fields=['patient', 'test'], name='core_patien_patient_e2202d_idx'),
        ),
        migrations.AddIndex(
            model_name='patienttest',
            index=models.Index(fields=['request_date'], name='core_patien_request_2f5893_idx'),
        ),
    ]
