# Generated by Django 5.2.7 on 2026-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='hematocrit',
            field=models.FloatField(blank=True, null=True, verbose_name='Hematocrit'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='hemoglobin',
            field=models.FloatField(blank=True, null=True, verbose_name='Hemoglobin'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='platelets',
            field=models.FloatField(blank=True, null=True, verbose_name='Platelets'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='rbc',
            field=models.FloatField(blank=True, null=True, verbose_name='RBC'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='wbc',
            field=models.FloatField(blank=True, null=True, verbose_name='WBC'),
        ),
    ]
